on:
  pull_request:
    paths:
      - 'src/WebUI/ClientApp/**'
    branches:
      - '**'
  push:
    paths:
      - 'src/WebUI/ClientApp/**'
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/WebUI/ClientApp

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, build, and test
      working-directory: ${{env.working-directory}}
      run: |
        npm ci
        npm run lint
        npm run build --if-present
        npm test
    - name: Archive integration test videos
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: integration-test-videos
        path: /home/runner/work/yap/yap/${{env.working-directory}}/cypress/videos
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: /home/runner/work/yap/yap/${{env.working-directory}}/coverage
    - name: send codecov
      working-directory: ${{env.working-directory}}
      run: |
        npm install -g codecov
        codecov
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
