on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run build --if-present
        npm test
    - name: send codecov
      run: |
        npm install -g codecov
        codecov
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Archive integration test videos
      uses: actions/upload-artifact@v1
      with:
        name: integration-test-videos
        path: /home/runner/work/yap/yap/cypress/videos
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage
        path: /home/runner/work/yap/yap/coverage
